### ISSUE TITLE
0.7.1Only ran it once, but created 4 vfs

### ISSUE THREAD

**Issue by wnark** [projectceladon/vm_manager#217]
CPU：12th Gen Intel(R) Core(TM) i5-12400
Base Board：ASUSTeK PRIME H610M-F D4 Rev 1.xx
VM_Manager version：0.7.1
Step：
1.https://docs.01.org/celadon/getting-started/on-vm.html
Refer to the tutorial to start a virtual machine
The configuration file is：
```
[global]
name=civ-2
flashfiles=/home/caas/caas-flashfiles-eng.celadon.zip
adb_port=5555
fastboot_port=5554

[emulator]
path=/usr/bin/qemu-system-x86_64

[memory]
size=4G

[vcpu]
num=1

[firmware]
type=unified
path=/home/caas/OVMF.fd

[disk]
size=30G
path=/home/caas/android.qcow2

[graphics]
type=SRIOV

[vtpm]
bin_path=/usr/bin/swtpm
data_dir=/home/caas/vtpm0

[rpmb]
bin_path=/home/caas/scripts/rpmb_dev
data_dir=/home/caas/rpmb

[aaf]
path=/home/caas/aaf

[extra]
cmd=-monitor stdio
```
2.When I only ran it once, it created four VFs。But the old version, when I tried it before, only created a vf once it started
![19b114c7cfdd8e32ff6f7e45797f4d1](https://user-images.githubusercontent.com/24355466/186833328-2b26cc32-1ce0-417a-862c-08ee5786f2e2.jpg)
![f3b46242812012b456967e192a455e1](https://user-images.githubusercontent.com/24355466/186833366-64a60433-fe95-484a-9a76-7a60fc96cad6.png)
![556df0f69618f0fd98d239cd3d08bec](https://user-images.githubusercontent.com/24355466/186833376-96fb9e5f-dcfd-4e84-9d2b-fb96adf87876.png)
![0be42a39883ab3cf94f48df5728b4b9](https://user-images.githubusercontent.com/24355466/186833405-373a5687-f219-4689-b631-40414e724ca2.png)
From the memory region info of the two pci devices, it can be seen that the first vf was assigned to celadon.  don't know how the other three vfs are separated.

**Comment by YadongQi** [comment]
Hi, @wnark. We do created 4 VFs when launch CiV with SRIOV. Current logic is:
```
if sriov_numvfs == 0
    create 4 VFs; # If other VMs want to use VF, then no need to disable VF and create VF again
else
    Try to find available VF from existing VFs.
fi
```
So, if you want only one VF, please create it before launch CiV(3. PCI Express I/O Virtualization Howto — The Linux Kernel  documentation). Hope this could solve your problem.
